### ISSUE TITLE
Error I/O

### ISSUE THREAD

**Issue by akshitasax** [gpask/PiSpy#6]
Hello,

I was recording a 12-hour video overnight using PiSpy, and when I checked on it in the morning, the video had not been saved anywhere and this was what the command line interface looked like (screenshot 1). I have used this raspberry pi computer and PiSpy user to record 12-hour videos before, so I don't understand what could have changed. What could this error be due to?
![2022-07-07-142454_1920x1080_scrot](https://user-images.githubusercontent.com/104799583/177895399-c3482c92-2f44-49e8-9c3f-da681ee79d19.png)
Screenshot 1

Another raspberry pi computer with PiSpy on it that I have been using to record 12-hour videos also showed a similar error when I tried to record a 12 hour video (screenshot 2). The video did save as an mp4, but it was unseekable, and could not be opened by the data extraction software I use post-recording. This error has never happened on this computer before.
![2022-07-07-160550_1920x1080_scrot](https://user-images.githubusercontent.com/104799583/177895425-31cec7f1-64da-40fb-bf0e-403a5b608231.png)
Screenshot 2

Is there anything I could do to fix this?

Thank you,
Akshita

**Comment by gpask** [comment]
Hi Akshita,

I spent the last week running the same settings that you were using and didn't encounter that error message or the issue with data being saved. We're a little at a loss too because we never saw that error in any of our testing as well, just like you haven't seen it on your other PiSpy devices.

Do you have any GPIO devices connected (seems like LED board based on your settings)? It could be a failed connection of some sort based on the "I/O" of the error message.

My best advice would be to reimage the RPi, which you can now easily do using a PiSpy disk image we just uploaded to GitHub. You can find updated instructions for this more streamlined installation in the user's guide. Please let us know if you still see the error in the future, and good luck!

Greg

**Comment by akshitasax** [comment]
Hi Greg,

Thank you for responding! We ended up reimaging the Rpi using SD cards with larger storage and that seemed to do the trick. Have not run into the same issue again since. 

Thanks again,
Akshita
